--INSERT TRIGGER QUERY 
CREATE TRIGGER TR_PERSON_MSG_INSERT
ON PERSON
AFTER INSERT 
AS
BEGIN 
PRINT 'RECORD IS INSERTED'
END

INSERT INTO PERSON VALUES (108 ,'KUNAL' , 'VANDRA' , 46000.00 , '1998-02-24' , 3 , 11)
INSERT INTO PERSON VALUES (109 ,'DHRUV' , 'TANK' , 54000.00 , '1998-04-11' , 2 , 12)



--DELETE TRIGGER QUERY
CREATE TRIGGER TR_PERSON_MSG_DELETE
ON PERSON
AFTER DELETE 
AS
BEGIN 
PRINT 'RECORD IS DELETED'
END

DELETE FROM PERSON WHERE WORKERID = 109
DELETE FROM PERSON WHERE WORKERID = 108

--UPPDATE TRIGGER QUERY
CREATE TRIGGER TR_PERSON_MSG_UPDATE
ON PERSON
AFTER UPDATE 
AS
BEGIN 
PRINT 'RECORD IS UPDATED'
END

UPDATE  PERSON  SET  FIRSTNAME ='RAHUL' WHERE WORKERID =101

--INSERT LOGON MASSAGE
CREATE TRIGGER INSERT_DEPARTMENT
ON DEPARTMENT
FOR INSERT
AS
BEGIN 
DECLARE @DEPARTMENTID INT
SELECT @DEPARTMENTID =DEPARTMENTID FROM INSERTED

INSERT INTO LOG_INSERT 
VALUES('RECORD WITH DEPARTMENTID =   ' +CAST(@DEPARTMENTID AS VARCHAR) + '  IS INSERTED ON' + CAST(GETDATE() AS VARCHAR(50)))

END


INSERT INTO DEPARTMENT VALUES (6 ,'MASTERS')
INSERT INTO DEPARTMENT VALUES (5 ,'GATE EXAMINARS')

--DELETE LOGON MASSAGE
CREATE TRIGGER DELETE_DEPARTMENT
ON DEPARTMENT
FOR DELETE
AS
BEGIN 
DECLARE @DEPARTMENTID INT
SELECT @DEPARTMENTID =DEPARTMENTID FROM DELETED

INSERT INTO LOG_INSERT 
VALUES('RECORD WITH DEPARTMENTID =   ' +CAST(@DEPARTMENTID AS VARCHAR) + '  IS DELETED ON' + CAST(GETDATE() AS VARCHAR(50)))

END


DELETE FROM DEPARTMENT WHERE DEPARTMENTID = 6

--UPDATE LOGON MASSAGE
CREATE TRIGGER UPDATE_DEPARTMENT
ON DEPARTMENT
FOR INSERT
AS
BEGIN 
DECLARE @DEPARTMENTID INT
SELECT @DEPARTMENTID =DEPARTMENTID FROM INSERTED

INSERT INTO LOG_INSERT 
VALUES('RECORD WITH DEPARTMENTID =   ' +CAST(@DEPARTMENTID AS VARCHAR) + '  IS UPDATED ON' + CAST(GETDATE() AS VARCHAR(50)))

END

UPDATE DEPARTMENT SET DEPARTMENTNAME ='NEW STUDENTS' WHERE DEPARTMENTID=5




SELECT * FROM DEPARTMENT
SELECT * FROM LOG_INSERT

CREATE TABLE LOG_INSERT
(MASSAGE VARCHAR(500)) 
